import { Injectable } from '@nestjs/common';
import { SalesReportData } from './sales-report.service';
import { ExpenseReportData } from './expense-report.service';
import { InventoryReportData } from './inventory-report.service';
import { ProcurementReportData } from './procurement-report.service';
import { FinancialReportData } from './financial-report.service';

// eslint-disable-next-line @typescript-eslint/no-require-imports
const PDFDocument = require('pdfkit');

@Injectable()
export class ReportPdfService {
  private readonly themeColor = '#263238';
  private readonly accentColor = '#009688';
  private readonly highlightColor = '#FFB300';
  private readonly textPrimary = '#263238';
  private readonly textSecondary = '#263238';
  private readonly bgLight = '#FAFAFA';

  private formatCurrency(amount: number): string {
    return new Intl.NumberFormat('en-UG', {
      style: 'currency',
      currency: 'UGX',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  }

  /**
   * Truncate text to a maximum length with ellipsis
   */
  private truncateText(text: string, maxLength: number): string {
    if (!text || text.length <= maxLength) {
      return text;
    }
    return text.substring(0, maxLength - 3) + '...';
  }

  private formatDate(dateStr: string): string {
    const [year, month, day] = dateStr.slice(0, 10).split('-').map(Number);
    return new Date(year, month - 1, day).toLocaleDateString('en-UG', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  }

  private drawHeader(
    doc: PDFKit.PDFDocument,
    title: string,
    branchName: string,
    dateRange: { startDate: string; endDate: string },
    pageWidth: number
  ): void {
    // Company name
    doc.fontSize(18).font('Helvetica-Bold').fillColor(this.themeColor).text('QWIK POS', 50, 45);

    // Report title
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .fillColor(this.themeColor)
      .text(title.toUpperCase(), 300, 45, { align: 'right' });

    doc.moveDown(1.5);

    // Info box
    const boxY = doc.y;
    doc.rect(50, boxY, pageWidth, 40).fill(this.bgLight);

    doc
      .fillColor(this.textSecondary)
      .fontSize(9)
      .font('Helvetica')
      .text('BRANCH', 65, boxY + 8);
    doc
      .fillColor(this.textPrimary)
      .fontSize(12)
      .font('Helvetica-Bold')
      .text(branchName, 65, boxY + 20);

    doc
      .fillColor(this.textSecondary)
      .fontSize(9)
      .font('Helvetica')
      .text('PERIOD', 250, boxY + 8);
    doc
      .fillColor(this.textPrimary)
      .fontSize(12)
      .font('Helvetica-Bold')
      .text(
        `${this.formatDate(dateRange.startDate)} - ${this.formatDate(dateRange.endDate)}`,
        250,
        boxY + 20
      );

    doc
      .fillColor(this.textSecondary)
      .fontSize(9)
      .font('Helvetica')
      .text('GENERATED', 450, boxY + 8);
    doc
      .fillColor(this.textPrimary)
      .fontSize(12)
      .font('Helvetica-Bold')
      .text(new Date().toLocaleDateString('en-UG'), 450, boxY + 20);

    doc.y = boxY + 55;
  }

  private drawSummaryCard(
    doc: PDFKit.PDFDocument,
    x: number,
    y: number,
    width: number,
    label: string,
    value: string
  ): void {
    doc.rect(x, y, width, 50).fill(this.bgLight);
    doc
      .fillColor(this.textSecondary)
      .fontSize(9)
      .font('Helvetica')
      .text(label, x + 10, y + 10, { width: width - 20 });
    doc
      .fillColor(this.textPrimary)
      .fontSize(14)
      .font('Helvetica-Bold')
      .text(value, x + 10, y + 26, { width: width - 20 });
  }

  private drawSectionTitle(doc: PDFKit.PDFDocument, title: string): void {
    doc.moveDown(1);
    doc.fillColor(this.themeColor).fontSize(12).font('Helvetica-Bold').text(title);
    doc.moveDown(0.5);
  }

  private drawTableHeader(
    doc: PDFKit.PDFDocument,
    columns: { label: string; x: number; width: number }[]
  ): number {
    const y = doc.y;
    doc.rect(50, y, doc.page.width - 100, 25).fill(this.themeColor);
    doc.fillColor('#FAFAFA').fontSize(9).font('Helvetica-Bold');

    for (const col of columns) {
      doc.text(col.label, col.x, y + 8, { width: col.width });
    }

    return y + 25;
  }

  private drawFooter(doc: PDFKit.PDFDocument, pageWidth: number): void {
    const currentY = doc.y;
    const footerY = doc.page.height - 50;
    doc
      .fillColor(this.textSecondary)
      .fontSize(8)
      .font('Helvetica')
      .text('Generated by QWIK POS Management System', 50, footerY, {
        width: pageWidth,
        align: 'center',
      });
    doc.y = currentY;
  }

  private ensureTableRow(
    doc: PDFKit.PDFDocument,
    tableY: number,
    columns: { label: string; x: number; width: number }[],
    pageWidth: number
  ): number {
    if (tableY + 20 <= doc.page.height - 65) return tableY;

    this.drawFooter(doc, pageWidth);
    doc.addPage();
    doc.y = 50;
    return this.drawTableHeader(doc, columns);
  }

  // Sales Report PDF
  async generateSalesReportPdf(data: SalesReportData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const pageWidth = doc.page.width - 100;

      this.drawHeader(doc, 'Sales Report', data.branch.name, data.dateRange, pageWidth);

      // Summary cards
      const cardWidth = (pageWidth - 20) / 4;
      const cardY = doc.y;
      this.drawSummaryCard(
        doc,
        50,
        cardY,
        cardWidth,
        'TOTAL REVENUE',
        this.formatCurrency(data.summary.totalRevenue)
      );
      this.drawSummaryCard(
        doc,
        55 + cardWidth,
        cardY,
        cardWidth,
        'GROSS PROFIT',
        this.formatCurrency(data.summary.grossProfit)
      );
      this.drawSummaryCard(
        doc,
        60 + cardWidth * 2,
        cardY,
        cardWidth,
        'TOTAL SALES',
        data.summary.totalSales.toString()
      );
      this.drawSummaryCard(
        doc,
        65 + cardWidth * 3,
        cardY,
        cardWidth,
        'COST OF GOODS SOLD',
        this.formatCurrency(data.summary.costOfGoodsSold)
      );

      doc.y = cardY + 65;

      // Top Products
      this.drawSectionTitle(doc, 'Top Selling Products');
      const columns = [
        { label: 'Product', x: 55, width: 140 },
        { label: 'Qty', x: 200, width: 45 },
        { label: 'Revenue', x: 250, width: 90 },
        { label: 'COGS', x: 345, width: 90 },
        { label: 'Profit', x: 440, width: 95 },
      ];
      let tableY = this.drawTableHeader(doc, columns);

      doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
      for (let i = 0; i < Math.min(data.topProducts.length, 10); i++) {
        tableY = this.ensureTableRow(doc, tableY, columns, pageWidth);
        const product = data.topProducts[i];
        if (i % 2 === 0) {
          doc.rect(50, tableY, pageWidth, 20).fill(this.bgLight);
        }
        doc.fillColor(this.textPrimary);
        doc.text(this.truncateText(product.productName, 26), 55, tableY + 6, { width: 140 });
        doc.text(product.quantitySold.toString(), 200, tableY + 6, { width: 45 });
        doc.text(this.formatCurrency(product.revenue), 250, tableY + 6, { width: 90 });
        doc.text(this.formatCurrency(product.cost), 345, tableY + 6, { width: 90 });
        doc.text(this.formatCurrency(product.profit), 440, tableY + 6, { width: 95 });
        tableY += 20;
      }

      // Sales by Status
      if (data.salesByStatus.length > 0) {
        doc.y = tableY + 10;
        this.drawSectionTitle(doc, 'Sales by Status');
        const statusColumns = [
          { label: 'Status', x: 55, width: 150 },
          { label: 'Count', x: 210, width: 80 },
          { label: 'Revenue', x: 300, width: 100 },
        ];
        tableY = this.drawTableHeader(doc, statusColumns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < data.salesByStatus.length; i++) {
          tableY = this.ensureTableRow(doc, tableY, statusColumns, pageWidth);
          const status = data.salesByStatus[i];
          if (i % 2 === 0) {
            doc.rect(50, tableY, pageWidth, 20).fill(this.bgLight);
          }
          doc.fillColor(this.textPrimary);
          doc.text(status.status.charAt(0).toUpperCase() + status.status.slice(1), 55, tableY + 6, {
            width: 150,
          });
          doc.text(status.count.toString(), 210, tableY + 6, { width: 80 });
          doc.text(this.formatCurrency(status.revenue), 300, tableY + 6, { width: 100 });
          tableY += 20;
        }
      }

      this.drawFooter(doc, pageWidth);
      doc.end();
    });
  }

  // Expense Report PDF
  async generateExpenseReportPdf(data: ExpenseReportData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const pageWidth = doc.page.width - 100;

      this.drawHeader(doc, 'Expense Report', data.branch.name, data.dateRange, pageWidth);

      // Summary cards
      const cardWidth = (pageWidth - 15) / 3;
      const cardY = doc.y;
      this.drawSummaryCard(
        doc,
        50,
        cardY,
        cardWidth,
        'APPROVED EXPENSES',
        this.formatCurrency(data.summary.approvedExpenses)
      );
      this.drawSummaryCard(
        doc,
        55 + cardWidth,
        cardY,
        cardWidth,
        'PENDING',
        this.formatCurrency(data.summary.pendingExpenses)
      );
      this.drawSummaryCard(
        doc,
        60 + cardWidth * 2,
        cardY,
        cardWidth,
        'TOTAL COUNT',
        data.summary.expenseCount.toString()
      );

      doc.y = cardY + 65;

      // Expenses by Category
      this.drawSectionTitle(doc, 'Expenses by Category');
      const columns = [
        { label: 'Category', x: 55, width: 150 },
        { label: 'Amount', x: 210, width: 100 },
        { label: 'Count', x: 320, width: 60 },
        { label: 'Percentage', x: 390, width: 80 },
      ];
      let tableY = this.drawTableHeader(doc, columns);

      doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
      for (let i = 0; i < data.byCategory.length; i++) {
        tableY = this.ensureTableRow(doc, tableY, columns, pageWidth);
        const cat = data.byCategory[i];
        if (i % 2 === 0) {
          doc.rect(50, tableY, pageWidth, 20).fill(this.bgLight);
        }
        doc.fillColor(this.textPrimary);
        doc.text(
          cat.category.charAt(0).toUpperCase() + cat.category.slice(1).replace('_', ' '),
          55,
          tableY + 6,
          { width: 150 }
        );
        doc.text(this.formatCurrency(cat.amount), 210, tableY + 6, { width: 100 });
        doc.text(cat.count.toString(), 320, tableY + 6, { width: 60 });
        doc.text(`${cat.percentage.toFixed(1)}%`, 390, tableY + 6, { width: 80 });
        tableY += 20;
      }

      // Top Expenses
      if (data.topExpenses.length > 0) {
        doc.y = tableY + 10;
        this.drawSectionTitle(doc, 'Top Expenses');
        const expColumns = [
          { label: 'Title', x: 55, width: 180 },
          { label: 'Category', x: 240, width: 100 },
          { label: 'Amount', x: 350, width: 100 },
        ];
        tableY = this.drawTableHeader(doc, expColumns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < Math.min(data.topExpenses.length, 8); i++) {
          tableY = this.ensureTableRow(doc, tableY, expColumns, pageWidth);
          const exp = data.topExpenses[i];
          if (i % 2 === 0) {
            doc.rect(50, tableY, pageWidth, 20).fill(this.bgLight);
          }
          doc.fillColor(this.textPrimary);
          doc.text(this.truncateText(exp.title, 35), 55, tableY + 6, { width: 180 });
          doc.text(exp.category.charAt(0).toUpperCase() + exp.category.slice(1), 240, tableY + 6, {
            width: 100,
          });
          doc.text(this.formatCurrency(exp.amount), 350, tableY + 6, { width: 100 });
          tableY += 20;
        }
      }

      this.drawFooter(doc, pageWidth);
      doc.end();
    });
  }

  // Inventory Report PDF
  async generateInventoryReportPdf(data: InventoryReportData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const pageWidth = doc.page.width - 100;

      // Simple header for inventory (no date range)
      doc.fontSize(18).font('Helvetica-Bold').fillColor(this.themeColor).text('QWIK POS', 50, 45);

      doc
        .fontSize(24)
        .font('Helvetica-Bold')
        .fillColor(this.themeColor)
        .text('INVENTORY REPORT', 300, 45, { align: 'right' });

      doc.moveDown(1.5);

      const boxY = doc.y;
      doc.rect(50, boxY, pageWidth, 40).fill(this.bgLight);

      doc
        .fillColor(this.textSecondary)
        .fontSize(9)
        .font('Helvetica')
        .text('BRANCH', 65, boxY + 8);
      doc
        .fillColor(this.textPrimary)
        .fontSize(12)
        .font('Helvetica-Bold')
        .text(data.branch.name, 65, boxY + 20);

      doc
        .fillColor(this.textSecondary)
        .fontSize(9)
        .font('Helvetica')
        .text('GENERATED', 450, boxY + 8);
      doc
        .fillColor(this.textPrimary)
        .fontSize(12)
        .font('Helvetica-Bold')
        .text(new Date().toLocaleDateString('en-UG'), 450, boxY + 20);

      doc.y = boxY + 55;

      // Summary cards
      const cardWidth = (pageWidth - 10) / 3;
      const cardY = doc.y;
      this.drawSummaryCard(
        doc,
        50,
        cardY,
        cardWidth,
        'TOTAL PRODUCTS',
        data.summary.totalProducts.toString()
      );
      this.drawSummaryCard(
        doc,
        55 + cardWidth,
        cardY,
        cardWidth,
        'RETAIL VALUE',
        this.formatCurrency(data.summary.totalRetailValue)
      );
      this.drawSummaryCard(
        doc,
        60 + cardWidth * 2,
        cardY,
        cardWidth,
        'COST VALUE',
        this.formatCurrency(data.summary.totalCostValue)
      );
      this.drawSummaryCard(
        doc,
        50,
        cardY + 60,
        cardWidth,
        'LOW STOCK',
        data.summary.lowStockCount.toString()
      );
      this.drawSummaryCard(
        doc,
        55 + cardWidth,
        cardY + 60,
        cardWidth,
        'OUT OF STOCK',
        data.summary.outOfStockCount.toString()
      );

      doc.y = cardY + 125;

      // Low Stock Products
      if (data.lowStockProducts.length > 0) {
        this.drawSectionTitle(doc, 'Low Stock Alert');
        const columns = [
          { label: 'Product', x: 55, width: 155 },
          { label: 'Qty', x: 215, width: 45 },
          { label: 'Threshold', x: 265, width: 60 },
          { label: 'Retail Price', x: 330, width: 95 },
          { label: 'Unit Cost', x: 430, width: 95 },
        ];
        let tableY = this.drawTableHeader(doc, columns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < Math.min(data.lowStockProducts.length, 15); i++) {
          tableY = this.ensureTableRow(doc, tableY, columns, pageWidth);
          const product = data.lowStockProducts[i];
          if (i % 2 === 0) {
            doc.rect(50, tableY, pageWidth, 20).fill(this.bgLight);
          }
          doc.fillColor(this.textPrimary);
          doc.text(this.truncateText(product.name, 30), 55, tableY + 6, { width: 155 });
          doc
            .fillColor(this.highlightColor)
            .text(product.quantity.toString(), 215, tableY + 6, { width: 45 });
          doc
            .fillColor(this.textPrimary)
            .text(product.lowStockThreshold.toString(), 265, tableY + 6, { width: 60 });
          doc.text(this.formatCurrency(product.price), 330, tableY + 6, { width: 95 });
          doc.text(this.formatCurrency(product.costPrice ?? 0), 430, tableY + 6, { width: 95 });
          tableY += 20;
        }
      }

      // Stock by Category
      if (data.stockByCategory.length > 0) {
        this.drawFooter(doc, pageWidth);
        doc.addPage();
        doc.y = 50;
        this.drawSectionTitle(doc, 'Stock by Category');
        const catColumns = [
          { label: 'Category', x: 55, width: 110 },
          { label: 'Products', x: 170, width: 55 },
          { label: 'Quantity', x: 230, width: 55 },
          { label: 'Retail Value', x: 290, width: 100 },
          { label: 'Cost Value', x: 395, width: 100 },
        ];
        let tableY = this.drawTableHeader(doc, catColumns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < data.stockByCategory.length; i++) {
          tableY = this.ensureTableRow(doc, tableY, catColumns, pageWidth);
          const cat = data.stockByCategory[i];
          if (i % 2 === 0) {
            doc.rect(50, tableY, pageWidth, 20).fill(this.bgLight);
          }
          doc.fillColor(this.textPrimary);
          doc.text(this.truncateText(cat.categoryName, 20), 55, tableY + 6, { width: 110 });
          doc.text(cat.productCount.toString(), 170, tableY + 6, { width: 55 });
          doc.text(cat.totalQuantity.toString(), 230, tableY + 6, { width: 55 });
          doc.text(this.formatCurrency(cat.totalRetailValue), 290, tableY + 6, { width: 100 });
          doc.text(this.formatCurrency(cat.totalCostValue), 395, tableY + 6, { width: 100 });
          tableY += 20;
        }
      }

      this.drawFooter(doc, pageWidth);
      doc.end();
    });
  }

  // Procurement Report PDF
  async generateProcurementReportPdf(data: ProcurementReportData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const pageWidth = doc.page.width - 100;

      this.drawHeader(doc, 'Procurement Report', data.branch.name, data.dateRange, pageWidth);

      // Summary cards
      const cardWidth = (pageWidth - 15) / 3;
      const cardY = doc.y;
      this.drawSummaryCard(
        doc,
        50,
        cardY,
        cardWidth,
        'TOTAL POs',
        data.summary.totalPurchaseOrders.toString()
      );
      this.drawSummaryCard(
        doc,
        55 + cardWidth,
        cardY,
        cardWidth,
        'TOTAL VALUE',
        this.formatCurrency(data.summary.totalAmount)
      );
      this.drawSummaryCard(
        doc,
        60 + cardWidth * 2,
        cardY,
        cardWidth,
        'RECEIVED VALUE',
        this.formatCurrency(data.summary.receivedAmount)
      );

      doc.y = cardY + 65;

      // PO by Status
      this.drawSectionTitle(doc, 'Purchase Orders by Status');
      const columns = [
        { label: 'Status', x: 55, width: 150 },
        { label: 'Count', x: 210, width: 70 },
        { label: 'Amount', x: 285, width: 100 },
        { label: '%', x: 390, width: 60 },
      ];
      let tableY = this.drawTableHeader(doc, columns);

      doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
      for (let i = 0; i < data.byStatus.length; i++) {
        tableY = this.ensureTableRow(doc, tableY, columns, pageWidth);
        const status = data.byStatus[i];
        if (i % 2 === 0) {
          doc.rect(50, tableY, pageWidth, 20).fill(this.bgLight);
        }
        doc.fillColor(this.textPrimary);
        doc.text(
          status.status.replace('_', ' ').charAt(0).toUpperCase() +
            status.status.replace('_', ' ').slice(1),
          55,
          tableY + 6,
          { width: 150 }
        );
        doc.text(status.count.toString(), 210, tableY + 6, { width: 70 });
        doc.text(this.formatCurrency(status.amount), 285, tableY + 6, { width: 100 });
        doc.text(`${status.percentage.toFixed(1)}%`, 390, tableY + 6, { width: 60 });
        tableY += 20;
      }

      // By Supplier
      if (data.bySupplier.length > 0) {
        doc.y = tableY + 10;
        this.drawSectionTitle(doc, 'Orders by Supplier');
        const supColumns = [
          { label: 'Supplier', x: 55, width: 180 },
          { label: 'Orders', x: 240, width: 70 },
          { label: 'Total Amount', x: 320, width: 120 },
        ];
        tableY = this.drawTableHeader(doc, supColumns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < Math.min(data.bySupplier.length, 10); i++) {
          tableY = this.ensureTableRow(doc, tableY, supColumns, pageWidth);
          const sup = data.bySupplier[i];
          if (i % 2 === 0) {
            doc.rect(50, tableY, pageWidth, 20).fill(this.bgLight);
          }
          doc.fillColor(this.textPrimary);
          doc.text(this.truncateText(sup.supplierName, 35), 55, tableY + 6, { width: 180 });
          doc.text(sup.orderCount.toString(), 240, tableY + 6, { width: 70 });
          doc.text(this.formatCurrency(sup.totalAmount), 320, tableY + 6, { width: 120 });
          tableY += 20;
        }
      }

      this.drawFooter(doc, pageWidth);
      doc.end();
    });
  }

  // Financial Report PDF
  async generateFinancialReportPdf(data: FinancialReportData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const pageWidth = doc.page.width - 100;

      this.drawHeader(doc, 'Financial Report', data.branch.name, data.dateRange, pageWidth);

      // Summary cards - Row 1: Revenue, Expenses, COGS, inventory cost
      const cardWidth = (pageWidth - 20) / 4;
      const cardGap = 5;
      const cardY = doc.y;
      this.drawSummaryCard(
        doc,
        50,
        cardY,
        cardWidth,
        'TOTAL REVENUE',
        this.formatCurrency(data.summary.totalRevenue)
      );
      this.drawSummaryCard(
        doc,
        50 + (cardWidth + cardGap),
        cardY,
        cardWidth,
        'TOTAL EXPENSES',
        this.formatCurrency(data.summary.totalExpenses)
      );
      this.drawSummaryCard(
        doc,
        50 + (cardWidth + cardGap) * 2,
        cardY,
        cardWidth,
        'COST OF GOODS SOLD',
        this.formatCurrency(data.summary.costOfGoodsSold)
      );
      this.drawSummaryCard(
        doc,
        50 + (cardWidth + cardGap) * 3,
        cardY,
        cardWidth,
        'COST OF AVAILABLE STOCK',
        this.formatCurrency(data.summary.totalCostOfAvailableStock)
      );

      // Row 2: Gross Profit, Net Profit, Gross Margin, Net Margin
      const row2Y = cardY + 60;

      // Gross profit card with color
      const grossProfitX = 50;
      doc.rect(grossProfitX, row2Y, cardWidth, 50).fill(this.bgLight);
      doc
        .fillColor(this.textSecondary)
        .fontSize(9)
        .font('Helvetica')
        .text('GROSS PROFIT', grossProfitX + 10, row2Y + 10, { width: cardWidth - 20 });
      doc
        .fillColor(data.summary.grossProfit >= 0 ? this.accentColor : this.highlightColor)
        .fontSize(14)
        .font('Helvetica-Bold')
        .text(this.formatCurrency(data.summary.grossProfit), grossProfitX + 10, row2Y + 26, {
          width: cardWidth - 20,
        });

      // Net profit card with color
      const netProfitX = 50 + (cardWidth + cardGap);
      doc.rect(netProfitX, row2Y, cardWidth, 50).fill(this.bgLight);
      doc
        .fillColor(this.textSecondary)
        .fontSize(9)
        .font('Helvetica')
        .text('NET PROFIT', netProfitX + 10, row2Y + 10, { width: cardWidth - 20 });
      doc
        .fillColor(data.summary.netProfit >= 0 ? this.accentColor : this.highlightColor)
        .fontSize(14)
        .font('Helvetica-Bold')
        .text(this.formatCurrency(data.summary.netProfit), netProfitX + 10, row2Y + 26, {
          width: cardWidth - 20,
        });

      this.drawSummaryCard(
        doc,
        50 + (cardWidth + cardGap) * 2,
        row2Y,
        cardWidth,
        'GROSS MARGIN',
        `${data.summary.grossProfitMargin.toFixed(1)}%`
      );
      this.drawSummaryCard(
        doc,
        50 + (cardWidth + cardGap) * 3,
        row2Y,
        cardWidth,
        'NET MARGIN',
        `${data.summary.profitMargin.toFixed(1)}%`
      );

      doc.y = row2Y + 65;

      // Monthly Breakdown
      if (data.monthlyBreakdown.length > 0) {
        this.drawSectionTitle(doc, 'Monthly Breakdown');
        const columns = [
          { label: 'Month', x: 55, width: 70 },
          { label: 'Revenue', x: 130, width: 90 },
          { label: 'COGS', x: 225, width: 90 },
          { label: 'Expenses', x: 320, width: 90 },
          { label: 'Profit', x: 415, width: 110 },
        ];
        let tableY = this.drawTableHeader(doc, columns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < data.monthlyBreakdown.length; i++) {
          tableY = this.ensureTableRow(doc, tableY, columns, pageWidth);
          const month = data.monthlyBreakdown[i];
          if (i % 2 === 0) {
            doc.rect(50, tableY, pageWidth, 20).fill(this.bgLight);
          }
          doc.fillColor(this.textPrimary);
          doc.text(month.month, 55, tableY + 6, { width: 70 });
          doc.text(this.formatCurrency(month.revenue), 130, tableY + 6, { width: 90 });
          doc.text(this.formatCurrency(month.cogs), 225, tableY + 6, { width: 90 });
          doc.text(this.formatCurrency(month.expenses), 320, tableY + 6, { width: 90 });
          doc.fillColor(month.profit >= 0 ? this.accentColor : this.highlightColor);
          doc.text(this.formatCurrency(month.profit), 415, tableY + 6, { width: 110 });
          tableY += 20;
        }
        doc.y = tableY;
      }

      if (data.revenueByCategory.length > 0) {
        doc.y += 20;
        this.drawSectionTitle(doc, 'Revenue by Product Category');
        const revenueColumns = [
          { label: 'Category', x: 55, width: 180 },
          { label: 'Revenue', x: 240, width: 120 },
          { label: 'Percentage', x: 370, width: 80 },
        ];
        let tableY = this.drawTableHeader(doc, revenueColumns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < data.revenueByCategory.length; i++) {
          tableY = this.ensureTableRow(doc, tableY, revenueColumns, pageWidth);
          const category = data.revenueByCategory[i];
          if (i % 2 === 0) doc.rect(50, tableY, pageWidth, 20).fill(this.bgLight);
          doc.fillColor(this.textPrimary);
          doc.text(this.truncateText(category.category, 35), 55, tableY + 6, { width: 180 });
          doc.text(this.formatCurrency(category.amount), 240, tableY + 6, { width: 120 });
          doc.text(`${category.percentage.toFixed(1)}%`, 370, tableY + 6, { width: 80 });
          tableY += 20;
        }
        doc.y = tableY;
      }

      // Expense by Category
      if (data.expenseByCategory.length > 0) {
        doc.y = doc.y + 20;
        this.drawSectionTitle(doc, 'Expense Breakdown by Category');
        const catColumns = [
          { label: 'Category', x: 55, width: 180 },
          { label: 'Amount', x: 240, width: 120 },
          { label: 'Percentage', x: 370, width: 80 },
        ];
        let tableY = this.drawTableHeader(doc, catColumns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < Math.min(data.expenseByCategory.length, 10); i++) {
          tableY = this.ensureTableRow(doc, tableY, catColumns, pageWidth);
          const cat = data.expenseByCategory[i];
          if (i % 2 === 0) {
            doc.rect(50, tableY, pageWidth, 20).fill(this.bgLight);
          }
          doc.fillColor(this.textPrimary);
          doc.text(
            cat.category.charAt(0).toUpperCase() + cat.category.slice(1).replace('_', ' '),
            55,
            tableY + 6,
            { width: 180 }
          );
          doc.text(this.formatCurrency(cat.amount), 240, tableY + 6, { width: 120 });
          doc.text(`${cat.percentage.toFixed(1)}%`, 370, tableY + 6, { width: 80 });
          tableY += 20;
        }
      }

      this.drawFooter(doc, pageWidth);
      doc.end();
    });
  }
}
